### ISSUE TITLE
throw exception when the statement missing the semicolon as splitter

### ISSUE THREAD

**Issue by CuteLemon** [reata/sqllineage#159]
I'm confused if the result is expected:

```MSSQL

--MSSQL
-- saved as test.sql
select *
into t_0
from t0

--notice that the there is no  semicolon between the two statement
select *
into t_1
from 
t1

-- also no semicolon 

drop table if exists t2;

select *
into t2
from t_1
union ALL
select * 
from t_0

```

> sqllineage -g -f test.sql

![image](https://user-images.githubusercontent.com/13835126/123034872-f5074800-d41c-11eb-88d0-e6e317c957ee.png)

If I add a semicolon between the first two statement, the graph output is normal.

**Comment by reata** [comment]
Sorry for the late reply. This is both expected and unexpected.

It's expected because as you can see from Text View in UI (or toggle -v for verbose option in command line), this SQL is recognized as 2 statements SQL. The first one clearly is syntactically wrong. But because we're using [sqlparse](https://github.com/andialbrecht/sqlparse) as parser, which according to its homepage, is a "non-validating SQL parser". In other words, we don't validate against the SQL syntax, we just try our best to parse it. This approach has its advantage and disadvantage. The disadvantage is obvious, we had this issue coming. On the other side, talking about the good part, personally I never used MSSQL before, so I'm amazed to see SQL like `select * into t_0 from t0` is valid and sqllineage even supports it.

And it's unexpected because as a user, I'd like the library to throw me an error, or at least give me some warnings in case like this, as opposed to just showing this confusing graph, which leads me nowhere for debugging. Of course it's user's responsibility to get the syntax right, whilst it's library's responsibility to at least warn the user about this. Although I have no clue at this point how we're going to detect potential syntax error so as to warn user, let's leave this ticket open for future reference.

**Comment by reata** [comment]
After releasing v1.4.0 next month, we shall be able to use --dialect=tsql in command line, or in python LineageRunner(sql, dialect="tsql") to leverage our new parsing capability. sqllineage will throw a InvalidSyntaxException for most syntax error.

However, this missing semicolon issue is not well handled yet, because it will be parsed as Batches of SQL Statements (https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/batches-of-sql-statements?view=sql-server-ver16)
 by mistake. We need to contact upstream sqlfluff for fix.

**Comment by reata** [comment]
We will close this issue as we already support throwing exception generally when semicolon is missing.

With tsql, I'm surprised to understand that semicolon is actually not a must-have. Currently after closing #422 , we trigger a SyntaxWarning, letting people know that SQLLineage is not guaranteed to output correct result with tsql when semicolon is missing. We'll try supporting that feature in #384 .
