### ISSUE TITLE
Snowflake - Error parsing MERGE statement

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [reata/sqllineage#166]
Hello,

I am obtaining an error parsing a specific merge statement. Here is my code and error:

Code:
```
bad_text = """
    merge into target using source
      on target.id = source.id
      when matched then update set
        target.c1 = source.c1,
        target.c2 = source.c2
      when not matched then insert (
            c1,
            c2
        ) values (
            c1,
            c2
        );
"""

from sqllineage.runner import LineageRunner
t = LineageRunner(bad_text)
print(t)
```

Error:
```
SQLLineageException                       Traceback (most recent call last)
/tmp/ipykernel_9799/2058247866.py in <module>
----> 1 print(t)

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/runner.py in wrapper(*args, **kwargs)
     18         self = args[0]
     19         if not self._evaluated:
---> 20             self._eval()
     21         return func(*args, **kwargs)
     22 

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/runner.py in _eval(self)
    145             if s.token_first(skip_cm=True)
    146         ]
--> 147         self._lineage_results = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
    148         self._combined_lineage_result = combine(*self._lineage_results)
    149         self._evaluated = True

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/runner.py in <listcomp>(.0)
    145             if s.token_first(skip_cm=True)
    146         ]
--> 147         self._lineage_results = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
    148         self._combined_lineage_result = combine(*self._lineage_results)
    149         self._evaluated = True

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/core.py in analyze(self, stmt)
     94         else:
     95             # DML parsing logic also applies to CREATE DDL
---> 96             self._extract_from_dml(stmt)
     97         return self._lineage_result
     98 

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/core.py in _extract_from_dml(self, token)
    155                 source_table_token_flag = False
    156             elif target_table_token_flag:
--> 157                 self._handle_target_table_token(sub_token)
    158                 target_table_token_flag = False
    159             elif temp_table_token_flag:

~/.virtualenvs/my-proj/lib/python3.9/site-packages/sqllineage/core.py in _handle_target_table_token(self, sub_token)
    216         else:
    217             if not isinstance(sub_token, Identifier):
--> 218                 raise SQLLineageException(
    219                     "An Identifier is expected, got %s[value: %s] instead."
    220                     % (type(sub_token).__name__, sub_token)

SQLLineageException: An Identifier is expected, got IdentifierList[value: target.c1 = source.c1,
    target.c2 = source.c2] instead.
```

Not sure if it might help identifying the problem, but removing one of the lines from the UPDATE statement turns it into a parsable statement, but gives an incorrect output:

```
# this works!
merge into target using source
on target.id = source.id
when matched then update set
      target.c1 = source.c1
when not matched then insert (
      c1,
      c2
) values (
      c1,
      c2
);
```

Output:
```
Statements(#): 1
Source Tables:
    source.c1
Target Tables:
    <default>.target
    target.c1
```

**Comment by reata** [comment]
Thanks for reporting this. The underlying reason is complicated here. Keyword "update" is used as an indicator for target table for UPDATE statement, so the next non keyword token is recognized as target table identifier, which clearly shouldn't apply here. 

In the first exception case, keyword "set" after "update" is ignored, so a token with value 'target.c1 = source.c1, target.c2 = source.c2' is detected and we throw an exception because it's IdentifierList instead of Identifier. In normal UPDATE statement, this is true. Updating multiple tables is not allowed in one UPDATE statement.

While in the second case, token "target.c1 = source.c1" is detected as target table and this time it's a Comparison as parsed by `sqlparse`. Previously we had a logic to handle "CREATE TABLE tab1 LIKE tab2" where "tab1 LIKE tab2" is a Comparison, with the similar pattern, target.c1 is parsed as target table while source.c1 is parsed as source table, and that's absolutely wrong because they're not even tables, they're columns. And column lineage is not yet supported.

With all this being said, this is a bug without doubt. But with current setting, it's kind of difficult to fix it with an elegant solution. I'll keep this open and think before implementation.

Plus, a fun fact: MERGE statement is not introduced to ANSI-SQL standard until SQL:2003, with "CREATE TABLE LIKE" introduced at the same year. See https://en.wikipedia.org/wiki/SQL:2003

**Comment by FredericoCoelhoNunes** [comment]
Hi @reata , first of all thanks for the answer and for the great work on this repository.

Just to make sure I understood: it's not easy to "fix" the merge statement in the current implementation, because it would interfere with the rules for other types of statements?

If that is the case, do you have any idea on when you might be available to fix this bug?

Alternatively, may I suggest that you create a small README with your "design philosophy" to guide possible contributors? In my case for example, my only knowledge about interpreters comes from [this series of articles](https://ruslanspivak.com/lsbasi-part1/), so these are the only design patterns I know for implementing parsers/interpreters. So it would definitely help me a lot to know what your vision is, so I could try to adapt to it in case I wanted to contribute!

Thanks!

**Comment by FredericoCoelhoNunes** [comment]
One more thing that I forgot to add: my company can provide me some work hours to help with this task, so if there is any way I can help work towards this, please let me know!

**Comment by reata** [comment]
Your understand is correct. The rule this "MERGE" statement interfere with is "CREATE TABLE LIKE". Previously I already use a hack to handle "CREATE TABLE LIKE"(see https://github.com/reata/sqllineage/issues/117 for reference), so if possible, I'd rather not patch this with another hack. 

I cannot give a precise ETA until I have time to look at this issue in detail next weekend.

As for the "design philosophy", we have a [contributing guide](https://github.com/reata/sqllineage/blob/master/CONTRIBUTING.md), although it's mainly focus on the toolchain and dev process side of the story. Personally I only have a very basic understanding of parser, after all, all you need is learn how to use a parser instead of building one. Most of my knowledge comes from using and reading the source code of [sqlparse](https://github.com/andialbrecht/sqlparse). I'd encourage you to try play with this library using your own SQL and then come back to see how sqllineage is leveraging it. Contribution is always welcome.

The long term vision is to replace sqlparse library with an in-house SQL parser, possibly built with [ANTLR](https://www.antlr.org/), so that we can create parser strictly to each SQL dialect specification, but that's really in the distant future.

**Comment by sudhanshu456** [comment]
Hey? @reata I'm have been working in parsing and lineage for over 1 yr in using python & java. I would like to contribute to the above issue. Let me know I can go ahead?

**Comment by reata** [comment]
> Hey? @reata I'm have been working in parsing and lineage for over 1 yr in using python & java. I would like to contribute to the above issue. Let me know I can go ahead?

Thanks for being interested in contributing. I'm holding on this issue because: 1) as mentioned above, it's kind of conflicting with "CREATE TABLE LIKE"; 2) the UPDATE keyword here is not a indicator for target table and we need to specially handle this; 3) I'm right now working on the column level lineage and the overall code structure may change substantially over next week.

Anyway, to start, besides my comment above, you can take a look at https://github.com/reata/sqllineage/blob/master/sqllineage/core/handlers/target.py, and let's discuss the solution carefully here before a submitting a PR. And thanks again, your participation is really appreciated.

**Comment by sudhanshu456** [comment]
@reata glad to hear you're working on column-level lineage let me know if you need any help! this will open so many other options going forward.

Fyi - I will take a look at the code source first.

**Comment by reata** [comment]
After v1.4.0 release when we introduce dialect-awareness lineage analysis, you shall get the following result:
```
$ sqllineage -f test.sql --dialect=ansi
Statements(#): 1
Source Tables:
    <default>.source
Target Tables:
    <default>.target

$ sqllineage -f test.sql --dialect=ansi -l column
<default>.target.c1 <- <default>.source.c1
<default>.target.c2 <- <default>.source.c2
```

MERGE statement is ANSI standard, while you can also specify dialect=snowflake to get the same result.
