### ISSUE TITLE
Lite version without visualization

### ISSUE THREAD

**Issue by alyiwang** [reata/sqllineage#216]
Do we have a way to install a "lite" version of `sqllineage` without all the visualization components? We want to use this in our project but would really love to limit the dependencies and sizes.

**Comment by reata** [comment]
Sorry for the late reply, been really busy recently.

Right now we don't have a systematic/elegant way to exclude visualization components since it's packaged as data into the whl file uploaded in pypi. And unlike optional python package, we don't have a way to exclude it in setup.py.

But if you really want to remove it, you can do it post-installation. Say your sqllineage is installed at `/usr/lib/python3.8/site-packages/sqllineage`, then you can safely remove `/usr/lib/python3.8/site-packages/sqllineage/build/*`, which is all the frontend files. The python part will stay fine if you only do this.

As of v1.3.3, it will save you around 17M space. Let me know if you have any other questions.

**Comment by reata** [comment]
Close this issue as no update for more than 6 months.
