### ISSUE TITLE
Unable to extract alias of columns using function with CTAS

### ISSUE THREAD

**Issue by chezou** [reata/sqllineage#253]
While `INSERT OVERWRITE TABLE` can extract aliases for columns with function, `CREATE TABLE ... AS` can't.

Expected columns:

```sh
$ sqllineage -l column -e "INSERT OVERWRITE TABLE tbl1
SELECT
  coalesce(t1.col1, 0) AS col1,
  IF(
    t1.col1 IS NOT NULL,
    1,
    NULL
  ) AS col3
FROM
  t1
"
<default>.tbl1.col1 <- <default>.t1.col1
<default>.tbl1.col3 <- <default>.t1.col1
```

Actual:

```sh
$ sqllineage -l column -e "CREATE TABLE tbl1 AS
SELECT
  coalesce(t1.col1, 0) AS col1,
  IF(
    t1.col1 IS NOT NULL,
    1,
    NULL
  ) AS col3
FROM
  t1
"
<default>.tbl1.coalesce <- <default>.t1.coalesce
<default>.tbl1.if <- <default>.t1.if
```

**Comment by chezou** [comment]
This is due to the upstream issue. See: https://github.com/andialbrecht/sqlparse/pull/662

**Comment by reata** [comment]
Wow, thanks. I know CTAS has some other parsing issue but wasn't aware of this. Let's see if your PR gets accepted. 

FYI, since sqlparse is not in active maintenance, I already had two monkey patches in https://github.com/reata/sqllineage/blob/master/sqllineage/__init__.py for sqlparse. So that's another way to solve it.

**Comment by chezou** [comment]
Created a PR to sqllineage at #258 
Let me know if it works for you.
