### ISSUE TITLE
Unable to extract column name when DIV exists

### ISSUE THREAD

**Issue by chezou** [reata/sqllineage#257]
While this is an upstream issue of sqlparse, `DIV` isn't treated as Operator, so it breaks column level parsing.

https://github.com/andialbrecht/sqlparse/issues/663

## Actual
```sh
$ .venv/bin/sqllineage -l column -e "INSERT OVERWRITE TABLE tab2
SELECT cast(conv(col1, 16, 10) as bigint) div 5 AS col2
FROM tab1"
<default>.tab2.div <- <default>.tab1.col1
```

## Expected

```sh
$ .venv/bin/sqllineage -l column -e "INSERT OVERWRITE TABLE tab2
SELECT cast(conv(col1, 16, 10) as bigint) div 5 AS col2
FROM tab1"
<default>.tab2.col2 <- <default>.tab1.col1
```

**Comment by reata** [comment]
Using DIV as a arithmetic operator is not a universally supported feature among different SQL dialect and DIV is not a keyword in ANSI-2016. **Overall I think it's nice that we can support this feature but I don't want to do it by introducing DIV as keyword with monkey patching.** 

Referring to issues like #93 and #183 , adding DIV as keyword will deprive us the ability to use DIV as table name or column name without quoting, which is a valid use case for most of the dialects except for MySQL because DIV in MySQL is reserved keyword.

```sql
INSERT INTO TABLE div
SELECT col AS div
FROM foo;
```

Reference:

SQL Dialect  | support DIV operator | keyword | Reference
-- | -- | -- | --
ANSI-2016 | N | not a keyword | https://en.wikipedia.org/wiki/SQL_reserved_words
MySQL | Y | reserved | https://dev.mysql.com/doc/refman/8.0/en/keywords.html
PostgreSQL | N | not a keyword | https://www.postgresql.org/docs/current/sql-keywords-appendix.html
Oracle | N | not a keyword | https://docs.oracle.com/cd/A97630_01/appdev.920/a42525/apb.htm
Hive | Y | not a keyword* | https://cwiki.apache.org/confluence/display/hive/languagemanual+ddl https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
SparkSQL | Y | Non-reserved | https://spark.apache.org/docs/latest/sql-ref-ansi-compliance.html
Trino | N | not a keyword | https://trino.io/docs/current/language/reserved.html

**support DIV operator**: Is SQL `SELECT 7 DIV 5` valid syntax?
**keyword**: Is SQL `SELECT 1 AS DIV` without quoting DIV valid syntax; This SQL only fails when DIV is reserved keyword. But Hive is special here that even though DIV is not a keyword in Hive, this query still throws exception for parsing issue.

**Comment by chezou** [comment]
Made some Googling and found a nice article https://hackernoon.com/14-open-source-sql-parsers

sqlparser-rs seems to support dialects in a good way, while we may introduce rust binding though https://github.com/sqlparser-rs/sqlparser-rs

**Comment by reata** [comment]
> Made some Googling and found a nice article https://hackernoon.com/14-open-source-sql-parsers
> 
> sqlparser-rs seems to support dialects in a good way, while we may introduce rust binding though https://github.com/sqlparser-rs/sqlparser-rs

Haha, I happen to read this article before. It's great.

Since I live in big data world especially with Spark, I'd prefer https://github.com/antlr/antlr4 a bit. 
On the other side, https://github.com/tobymao/sqlglot is a very good Python hand-written parser. Although I didn't dive deep, it makes very good first impression on me.
For https://github.com/sqlparser-rs/sqlparser-rs, unfortunately I'm not familiar with rust so I don't know.

**Comment by chezou** [comment]
While we discussed this topic deeply, the upstream of sqlparse merged my patch.
https://github.com/andialbrecht/sqlparse/issues/663#event-7145034206

Will close this issue.

**Comment by reata** [comment]
> While we discussed this topic deeply, the upstream of sqlparse merged my patch. [andialbrecht/sqlparse#663 (comment)](https://github.com/andialbrecht/sqlparse/issues/663#event-7145034206)
> 
> This means sqlparse 0.4.3 changes their behavior on `DIV` operator: https://github.com/andialbrecht/sqlparse/milestone/26
> 
> Will close this issue.

Wow, congratulations!
