### ISSUE TITLE
Cannot handle rename statement

### ISSUE THREAD

**Issue by HuanjieGuo** [reata/sqllineage#267]
rename table db1.a to db2.b;

**result**
target tables [db1.a]
source tables []

**It should be** 
target tables [db2.b]
source tables [db1.a]

**Comment by reata** [comment]
As of v1.3.5, only 'ALTER TABLE tbl_name RENAME TO new_tbl_name' is supported. This 'RENAME TABLE tbl_name to new_tbl_name' syntax is new to me. Is it MySQL you're using?
Ref: https://dev.mysql.com/doc/refman/8.0/en/rename-table.html

**Comment by HuanjieGuo** [comment]
Yes, my wrong.  I just used it to parse MySQL statements last time.  Forget to see what kinds of SQL it supports.

**Comment by reata** [comment]
Now RENAME statement is supported after #282 is merged.

But please be aware that for rename SQL, either: 1) alter table tbl_name rename to new_tbl_name; 2) rename table tbl_name to new_tbl_name:

1. We don't model rename relation as source table to-> target table. source table -> target table only applies when there is data flow from source table to target table.
2. The rename relation is kept separately at SQL statement level. We use this information at multi-statement level DAG assembly. For example, the following table will have lineage tab2 -> tab3, instead of tab2 -> tab1.
```sql
insert overwrite tab1 select * from tab2; alter table tab1 rename to tab3
```

**Comment by HuanjieGuo** [comment]
Thanks for your amazing parser! ! !
