### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [reata/sqllineage#284]
Hello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/sqllineage-feedstock

**Comment by reata** [comment]
Thanks for your effort. It's great that people can install sqllineage via conda. I know conda is popular among data science community, but personally I don't have much experience in this area.

Would you kindly give me some more information?

1. What's the workflow for publishing a conda forge packages? Is this process automated? I assume the building and publishing part is automated, but how does it detecting new publish in PyPI?
2. What are the typical things we need to do to maintain such a conda forge repo like https://github.com/conda-forge/sqllineage-feedstock?
3. What's the difference between a conda package and a PyPI package? Since sqllineage doesn't include any binary and the only non-Python part (the compiled html, js, css) is cross-platform, is there any particular reason we need a conda distributin?

**Comment by thewchan** [comment]
@reata 

1. It is automatic. If updates (e.g. to dependencies) are needed usually we find out when CI test fails. We can then update the recipe as need. Any maintainers on the feedstock can do this.
2. Virtually no work needed, the feedstock is already made. Maintainers merge bot generated PRs when upstream package is made (pushed to PyPI), and update recipe (see 1) when needed.
3. Conda packages are prebuild binaries. They are stored on Conda's own repo, and the main advantage is that they integrate very nicely with those using Conda environment and dependency management. PyPI packages can be installed to Conda virtual environment, but Conda cannot track pip-installed packages for dependency-management purposes.

**Comment by reata** [comment]
Thank you for your detailed explanation. I learned a lot. 

Considering not much work needed and conda forge is supposed to be community-based distribution. I'll pass for the ownership. But if there's anything else I can help in the future, don't hesitate to let me know. 

Thanks again for your effort.

**Comment by thewchan** [comment]
Thanks @reata, if this changes in the future you know where to find me!
