### ISSUE TITLE
Breaks when semicolon missing, but 'GO' present (t-sql)

### ISSUE THREAD

**Issue by dvasdekis** [reata/sqllineage#289]
Firstly, just wanted to say thank you for such an awesome library. We're using it to help environmental scientists with their data needs, so not sure if you've intended to help the environment as a side effect, but you've done so!

We've got a case where we write migrations in T-SQL, which uses `GO` as a splitter of statements. Example below, which is valid T-SQL:
```sql
CREATE  or ALTER VIEW [curated].[view1b] as
SELECT * FROM [raw].[view1a]
GO

CREATE OR ALTER VIEW [curated].[view2b] AS
SELECT * FROM [landing].[view2a]
GO

CREATE OR ALTER VIEW [curated].[view3b] AS
SELECT * FROM [raw].[view3a]
GO
```
yields:
```bash
PS C:\proj\> sqllineage -f .\331_lineagetry.sql
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\sqllineage.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\sqllineage\cli.py", line 86, in main
    runner.print_table_lineage()
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 166, in print_table_lineage
    print(str(self))
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 22, in wrapper
    self._eval()
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 179, in _eval
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 179, in <listcomp>
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "C:\Python310\lib\site-packages\sqllineage\core\analyzer.py", line 60, in analyze
    self._extract_from_dml(stmt, AnalyzerContext())
  File "C:\Python310\lib\site-packages\sqllineage\core\analyzer.py", line 139, in _extract_from_dml
    next_handler.end_of_query_cleanup(holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\source.py", line 112, in end_of_query_cleanup
    raise SQLLineageException
sqllineage.exceptions.SQLLineageException
```

Changing it to the below works perfectly, but is thankfully still valid T-SQL:
```sql
CREATE  or ALTER VIEW [curated].[view1b] as
SELECT * FROM [raw].[view1a];
GO

CREATE OR ALTER VIEW [curated].[view2b] AS
SELECT * FROM [landing].[view2a];
GO

CREATE OR ALTER VIEW [curated].[view3b] AS
SELECT * FROM [raw].[view3a];
GO
```
yields:
```bash
PS C:\proj\> sqllineage -f .\331_lineagetry.sql
Statements(#): 5
Source Tables:
    [landing].[view2a]
    [raw].[view1a]
    [raw].[view3a]
Target Tables:
    [curated].[view1b]
    [curated].[view2b]
    [curated].[view3b]
```

We've got way too much SQL to rewrite this way, but I'm happy to dig into creating some sqlparse improvements to support it. Sadly though, sqlparse isn't being updated very often - [this PR dates back to 2019](https://github.com/andialbrecht/sqlparse/pull/501) and still hasn't been merged.

Any thoughts on the best way I can extend your library with `GO` statement support?

THanks again!

**Comment by reata** [comment]
Thanks for your kind message. Environmental scientists (and their data engineer) rock!

For 'GO' in T-SQL, I made some study. In particular, I read this docs from Microsoft site: https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver16. Quoting from this article:
> SQL Server provides commands that are not Transact-SQL statements, but are recognized by the sqlcmd and osql utilities and SQL Server Management Studio Code Editor.

Since it's not a SQL statement (it's a Utilities Statement so called), not to mention it's T-SQL only. I'd advise against adding it to parser. sqlcmd and osql must have some utility function to deal with it, rather than relying on the AST returned by T-SQL parser. 

With that being said, if it was me, I would write a pre-processing function to detect the GO statement. A simple regular expression should do the trick, how about `^\s*GO\s*(\d+)?\s*`. After that, you can decide whether to replace it with semicolon or just split the raw file then feed each piece to sqllineage.

**Comment by dvasdekis** [comment]
Thanks for the tip, I'll add them into the code as, like you say, they become correct SQL with the semicolon. Thanks for the study!
