### ISSUE TITLE
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Token[value: *] instead.

### ISSUE THREAD

**Issue by micaimanong1** [reata/sqllineage#335]
hi  :
First of all, thank you for your efforts. 
I have an error

error :

sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Token[value: *] instead.

python code

`

from sqllineage.runner import LineageRunner
def test_create_as():
    sql2="""
     CREATE temporary TABLE temp AS
     SELECT *
     FROM dw_${city}.dwd_master_c
      WHERE type = 100;
    """
    result = LineageRunner(sql2.replace("${city}",'us'))
    print(result.source_tables)
    print(result.target_tables)

if __name__ == "__main__":
    test_create_as()

`

  Best regards .

**Comment by reata** [comment]
Thank you for reporting this issue. This is actually already fixed in master branch. We will release it with other features before end of Q1.

Underneath this is due to `temp` being keyword in certain sql dialect. In short term, it will work fine if you can change the table name, or disable this keyword explicitly before calling sqllineage via
```
from sqlparse.keywords import KEYWORDS
del KEYWORDS["TEMP"]
```
