### ISSUE TITLE
subquery mistake alias as table name in visualiztion

### ISSUE THREAD

**Issue by shengkui** [reata/sqllineage#512]
**Describe the bug**

Alias of a subquery show as a Table node in Visualizes Table/Column Lineage

**SQL**

```sql
CREATE TABLE main.tab1 AS (
  SELECT * FROM (
    SELECT T0.* FROM (SELECT * FROM main.tab0) T0 WHERE T0.num < 100
  )
)
```

**To Reproduce**
*Note here we refer to SQL provided in prior step as stored in a file named `test.sql`*

    sqllineage -f test.sql --dialect=ansi -g

Web UI (Web User Interface): 

<img width="385" alt="alias_table" src="https://github.com/reata/sqllineage/assets/17078500/7110a38e-f4a4-4b85-9074-6b18444c8181">

**Expected behavior**

There should be no table node for alias of subquery.

**Python version (available via `python --version`)**

 - 3.10.13

**SQLLineage version (available via `sqllineage --version`):**

 - 1.4.9

**Comment by reata** [comment]
Bug confirmed. Thanks for reporting.

**Comment by reata** [comment]
This is a regression issue introduced in v1.4.9 via https://github.com/reata/sqllineage/commit/fbad73abf65be8ef0f6e60f34b52d0675bf8abbc, v1.4.8 was OK.

The commit is to make subquery alias case insensitive. So that we can resolve `SELECT t0.* FROM (SELECT * FROM main.tab0) T0` correctly.

But that was only half done. Qualifier name was not converted to lower case correctly.
