### ISSUE TITLE
Incorrect Result for Cases When Non-Reserved Keyword Used as Table Name

### ISSUE THREAD

**Issue by coldmoutain** [reata/sqllineage#93]
hello,reata:
I got the newest code from your github to test whether SQLLINEAGE works.
it works very well for most of  cartesian product SQL.
 but ,when i input sql " select a.* from table a,table b" something strange happened:
### ` LineageRunner("select a.* from source a,source b").source_tables`  returns "[Table: <default>.a]" but not " table"
I run this sql just for fun ,after found this BUG .I tested more and get another "strange returns"
` LineageRunner("select a.* from source1 a,source b").source_tables` returns " [Table: <default>.source1]"
I thought , Was it the Tablenames matter? so I changed the Tablenames
`LineageRunner("select * from care a,care b").source_tables` returns "[Table: <default>.care]",It works.
`LineageRunner("select * from care1 a,care b").source_tables` returns "[Table: <default>.care, Table: <default>.care1]" It works well.
### `LineageRunner("select * from care a,care b").source_tables` returns "[Table: <default>.care]" but not "a" 

well,I thought that maybe some Tablenames sqllineage can`t works well.

**Comment by reata** [comment]
Thanks for reporting this. It's interesting. Let me check.

**Comment by reata** [comment]
```python
>>> from sqllineage.runner import LineageRunner
>>> print(LineageRunner("select a.* from source a,source b").source_tables)
[Table: <default>.a]
>>> print(LineageRunner("select a.* from source1 a,source b").source_tables)
[Table: <default>.source1]
>>> print(LineageRunner("select * from care a,care b").source_tables)
[Table: <default>.care]
>>> print(LineageRunner("select * from care1 a,care b").source_tables)
[Table: <default>.care, Table: <default>.care1]
```

The first two lineage are wrong. No. 1 should be [Table: <default>.source] and No. 2 should be [Table: <default>.source, Table: <default>.source1]. And the last two lineage are correct.

Actually You're unlucky to hit a corner case again. This issue arises from the fact that `source` is a keyword in SQL language, even though it's not reserved keyword like `select` or `insert`). See https://dev.mysql.com/doc/refman/8.0/en/keywords.html for reference.

It's definitely a bug. However, it will take some time for an elegant solution since I can't distinguish reserved keyword or any regular keyword right now.

**Comment by reata** [comment]
As a short term solution, you can try escape the table name source with back tick in MySQL:
```python
>>> print(LineageRunner("select a.* from `source` a,`source` b").source_tables)
[Table: <default>.source]
>>> print(LineageRunner("select a.* from source1 a, `source` b").source_tables)
[Table: <default>.source, Table: <default>.source1]
```

I just merge a PR, so you have to reinstall sqllineage from master branch. Let me know if this works for you. Meantime, I'll try to make it work even without table name escape.

**Comment by coldmoutain** [comment]
I got it .In fact ,I  used the SQL keywords to  test the cartesian product SQL using in sqllineage ,just for fun. I have reinstall sqllineage  and It works

**Comment by reata** [comment]
In dependency `sqlparse`:

1. There's no way to distinguish reserved keyword and non reserved keyword.
2. Keyword is actually parsed as `sqlparse.sql.Token` with ttype as 'Keyword', rather than `sqlparse.sql.Identifier`. 

All things considered, it's not easy for us even to hack through with current `sqlparse` design. So I'll raise an issue to `sqlparse` later to see what will happen next.

**Comment by reata** [comment]
Met a similar case today with non-reserved keyword `segment` used as table name
```sql
CREATE TABLE segment AS SELECT * FROM tab
```

sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Token[value: *] instead

**Comment by reata** [comment]
I was thinking of manually maintain a list of RESERVED_KEYWORDS, and mark non reserved keyword followed by keyword indicator as valid table name.

But as I tried, it turns out that this approach still doesn't fit into the current design. In particular, it conflicts with 
```
CREATE TABLE IF NOT EXISTS ...
```
where IF is a non reserved keyword, but we can't mark IF as table name.

**Comment by reata** [comment]
This becomes even more complicated when considering non reserved keyword used with alias or as CTE, 

- the alias or CTE subquery won't be grouped together as a identifier, so we lose some information.
- We cannot monkey patch sqlparse's lexer by changing these targeted T.Keyword to T.Name so group identifier works. Because at lexer level, we can't deal with nested structure like subquery

I've tried but I don't see any solutions here other than replace sqlparse to parser with syntax validation.

several test cases for future reference:
```python
def test_non_reserved_keyword_as_source():
    assert_table_lineage_equal("SELECT col1, col2 FROM segment", {"segment"})


def test_non_reserved_keyword_as_target():
    assert_table_lineage_equal("INSERT OVERWRITE TABLE host SELECT col1, col2 FROM segment", {"segment"}, {"host"})


def test_non_reserved_keyword_as_source_and_target():
    assert_table_lineage_equal("INSERT OVERWRITE TABLE host SELECT a.col1, a.col2 FROM segment a", {"segment"},
                               {"host"})
    assert_column_lineage_equal("INSERT OVERWRITE TABLE host SELECT a.col1, a.col2 FROM segment a",
                                [
                                    (
                                        ColumnQualifierTuple("col1", "segment"),
                                        ColumnQualifierTuple("col1", "host"),
                                    ),
                                    (
                                        ColumnQualifierTuple("col2", "segment"),
                                        ColumnQualifierTuple("col2", "host"),
                                    ),
                                ])


def test_non_reserved_keyword_as_cte():
    assert_table_lineage_equal(
        "WITH summary AS (SELECT * FROM segment) INSERT OVERWRITE TABLE host SELECT * FROM summary", {"segment"},
        {"host"})

```

**Comment by reata** [comment]
After we release v1.4.0 next month, you shall be able to use --dialect=ansi in command line, or in python LineageRunner(sql, dialect="ansi") to leverage our new parsing capability and get the correct result. Non-reserved keyword will not be a problem anymore. And there's more dialect choices like sparksql, hive, mysql, oracle, etc.
